### ISSUE TITLE
How to register new account with captcha ?

### ISSUE THREAD

**Issue by victor-pashuk** [nathan130200/AgsXMPP#4]
I understand that we need to fill form in OnRegisterInformation event, but how to send response to server ? 
Can you give a  small example?

**Comment by nathan130200** [comment]
You can bind event and set values in event handler:

```cs
connection.OnRegisterInformation  += (sender, e) => 
{
  e.Auto = false;
  e.Register = new Register("user", "pass");
};
```

Or you can just pass `e.Auto = true;` then username/password will be same you set in `XmppClientConnection`.

When this event is invoked, will collect these values and will send response to the server.

**Comment by victor-pashuk** [comment]
Thanks for response. Can you explain please, where i need to pass a captcha value?  Do i rigtht understand that in an "ocr" field of  innerXml field in Register object?Just we haven't an "Captcha" field in Register object.
 
I have innerXml like this :
`<instructions xmlns="jabber:iq:register">You need a client that supports x:data and CAPTCHA to register</instructions><x xmlns="jabber:x:data" type="form"><field var="FORM_TYPE" type="hidden"><value>urn:xmpp:captcha</value></field><instructions>Choose a username to register with this server. Set email or mobile phone number where your password will be sent</instructions><field type="text-single" var="username" label="User"><required /></field><field type="text-single" var="email" label="Email" /><field type="text-single" var="phone" label="Phone"><value>+</value></field><field type="fixed"><value>If you don't see the CAPTCHA image here, visit the web page.</value></field><field var="captchahidden" type="hidden"><value>workaround-for-psi</value></field><field type="text-single" var="url" label="CAPTCHA web page"><value>http://captcha.jabber.ru/captcha/17806757984532117430-416539273465935973416568419345504067170065085267/image</value></field><field var="from" type="hidden"><value>jabber.ru</value></field><field var="challenge" type="hidden"><value>17806757984532117430-416539273465935973416568419345504067170065085267</value></field><field var="sid" type="hidden"><value>agsXMPP_1</value></field><field var="ocr" label="Enter the text you see"><required /><media xmlns="urn:xmpp:media-element"><uri type="image/png">cid:sha1+2678d6c5fcbe47d73abd9d2f73daca5ed8594dea@bob.xmpp.org</uri></media></field></x><data xmlns="urn:xmpp:bob" type="image/png" max-age="0" cid="sha1+2678d6c5fcbe47d73abd9d2f73daca5ed8594dea@bob.xmpp.org">iVBORw0KGgoAAAANSUhEUgAAAIwAAAA8CAIAAAFMb/WKAAAFiElEQVR4nO1b0ZLbMAh0Ov3/X3YfPKcSWGCRUOKk3Yeb2JEAAQKEco/zPI9nPB4P+1Lhl5pgScBpOeGcmyKvWD19NbgxSwLczvMc9LwlAW4l/OWWcoi4lY12HAc0PZ4DZbteSiU9zZHav/4GQmLZFAk12VWdmiwHzFhJyybhuSLmoxQAV1XyVSAdtMp5npboGEN63ozuqqu5ADSeysh4M8XJs5xHd0l7nn7m9BZxaiFNcRoMoH93csJDzSZb2k+SkPpsNxnPJuIkCQ1Nev496eXWiaFb2/XF/GbyknSTa/x8Ngukk0QVm3hNUfyP2SjhUrix/DDuZ0VWPGKWQHueEmTuUBURUx1R9ocbthobozIxYDOBmkfY7TzPSRkgIFcqJwEnxTVgU01gfemnL5MtgnWIoIy4wFcxKj4/fkBKkqIWt+2jGpnmhR1VgxZjsTDik1NMLdaU9xUE5XiBY8ijknQh610xC5kk7GmMybID1JI8okru8weHWOpE/W599aiEn2RJMZVS/oT7ynvcUrxK0tIOdgwZ64Jqyjq2dQp+Yb/jr21XYSDwhJJegxJF+m1zeBjMmAFQtepDoH772Ox4AezWV9HvetmYQ0nkSwpMH1fu3qzdmLfSbZEvKU5zNylVJe5SPjdivlE0Xl4f7qOaJC+luM9KBgrhgay11Qc4ZmtkZx2PaW8c5vaCPIwdrdZePeeU+TmFbCMLKtWmXZX4TC7hrSHI2lWweSlF2pzw3rf7Xi3iWYvZox7ZppI7M1jVxPmitqSAKN/DUMcHO1dGGu/0HoDtPUC69hGa4niuqi6zxM2J4LyYIr/qZZpEg6sUPYgNdrpc5yLyg3rg60xnQgoKFyktGayZX+2WvAQ7b2o7HX5AX4yB8zUe03uQRvYsHPQe5rDxCGgjmx3AECFHDrCtyRJdFfrSLddbyK5ayQvrjBbSwDCHpQ4RfB/sHzjYzrVcSgsu3C+RdK0QNojbFGzT9DTYphdZKc8V1OcPqhMhyqdaWLmQe6YKS5bRV3kvyXwCc6IyVO+ZnNHO/HkpcBVVpKYsejFz/WwfIVaq6RW8tIG8tTE0QF2ZfRZYK8Ej9D0XPFmJ37DJOpBfP/dao0ptgvW/fXNRo8tpF27R79PyIlbvYiAaFU12mb4b/UbyiueqcoNZE/2qHRckL0OzkawKVGeTp3OEJwDe8J5V4LHoXUeHGG1Gal8e0yYjpYLvIf33nvI8rBpprKfa2pKAvWaPkZwVxy5P12nEG6a6iZ2WjFRt63lE1Ac7fjDiOcZ7JSU+d+xYvG3xsKW6k4jFVapM10YmIW9kelk35CkFBts1ToUsodNIVjtpOIKeG8Sx2NmhAAfSuFfsxXcWkIJFGoer6GnfjeuGacnUXKgR5sxkRzLKtY0Q9aZUoLYns3kjjSQ/zLPS8Kl2KB7o5nYi7AyvJ92iJGQXVm8zg91DFlHMSDhXsrY2Wy9qBn2v2hy7bd+N04VP+rn7idq9MDPFFoKbXhaZcIParTasuLtSf4+RqkWdHAnj0vn8c62q1qQ8sEaHn8cbaeAdBlvKSerRllWbABNSCWozlbzEsr7vTmo50xyErmX0l5SnFT3Ge6zJpW11RIm2Erw0mFeoKr16YwtTkQZcTvMjlU1bqsdIL/AsmaJtbl8h61FLCxAp2N7wvjueApbcr3EfqKXGk+UZrQB2QG50TpKAZbHnobHixixZbjFBaUrwJVjh5dGqUaSNDVZY7HlNmrFg6IZneMsXfPUu2LWviNdgJLL74s0lz4My9KsIcyvzWKyL17OTvP1hsZgYeEbfhP6Ow1vSA8TXWPSTendVpF2+T0HDvylNd4M+V2svRn91R15PpCP/Y6Cturubxl/f8N1Iv1G597TWF+AuPy37jwB/AIxRgvpDmnryAAAAAElFTkSuQmCC</data>`

**Comment by nathan130200** [comment]
The problem is because the server uses Jabber Captcha Forms (XEP-0158: https://xmpp.org/extensions/xep-0158.html) unfortunately this Jabber feature isn't implemented in this library, but you can try modify `Register` element like:

```cs
connection.OnRegisterInformation  += (sender, e) => 
{
	e.Auto = false; // must be false, because we need to manually fill informations.
	
	var form = e.Register.SelectSingleElement<Data>(); // Import 'AgsXMPP.Protocol.X.Data' namespace!
	var result = new Data();
	
	// for each field, you need set manually values.
	// fields are identified by 'var' attribute.
	
	result.AddField(new Field(FieldType.Text_Single) { Var = "username" }).SetValue("set value here");
	result.AddField(new Field(FieldType.Text_Single) { Var = "phone" }).SetValue("set value here");
	result.AddField(new Field(FieldType.Text_Single) { Var = "username" }).SetValue("set value here");
	
	e.Register = new Register();
	e.Register.AddChild(result); // append <x xmlns='jabber:x:data'>...</x> element to register
};
```

**Comment by victor-pashuk** [comment]
Ok.thanks

**Comment by victor-pashuk** [comment]
Sorry, but what we need to do with "form" variable in ur code? This variable didn't used in example.

**Comment by victor-pashuk** [comment]
Ok,i did it, sorry for waste of ur time)

**Comment by nathan130200** [comment]
The "form" variable is to determine how may features (`var="..."`) is required.
