### ISSUE TITLE
XMPP registration with captcha - failed with response  cancel "405" not-allowed

### ISSUE THREAD

**Issue by victor-pashuk** [nathan130200/AgsXMPP#5]
I try to register new account with a captcha , but registration failed.
I filled all fields in xdata, but it still crushes.
My request:
`"<instructions xmlns=\"jabber:x:data\">Choose a username and password to register with this server</instructions><field xmlns=\"jabber:x:data\" type=\"hidden\" var=\"FORM_TYPE\"><value>urn:xmpp:captcha</value></field><field xmlns=\"jabber:x:data\" label=\"User\" var=\"username\" type=\"text-single\"><required /><value>victorsps</value></field><field xmlns=\"jabber:x:data\" label=\"Password\" var=\"password\" type=\"text-private\"><required /><value>a25160920</value></field><field xmlns=\"jabber:x:data\" type=\"fixed\" var=\"captcha-fallback-text\"><value>If you don't see the CAPTCHA image here, visit the web page.</value></field><field xmlns=\"jabber:x:data\" type=\"hidden\" var=\"captchahidden\"><value>workaround-for-psi</value></field><field xmlns=\"jabber:x:data\" label=\"CAPTCHA web page\" var=\"captcha-fallback-url\" type=\"text-single\"><value>http://jabber.freenet.de/captcha/13382908590620806174/image</value></field><field xmlns=\"jabber:x:data\" type=\"hidden\" var=\"from\"><value>jabber.freenet.de</value></field><field xmlns=\"jabber:x:data\" type=\"hidden\" var=\"challenge\"><value>13382908590620806174</value></field><field xmlns=\"jabber:x:data\" type=\"hidden\" var=\"sid\"><value>agsXMPP_1</value></field><field xmlns=\"jabber:x:data\" label=\"Enter the text you see\" var=\"ocr\" type=\"text-single\"><media xmlns=\"urn:xmpp:media-element\"><uri type=\"image/png\">cid:sha1+fc7819bf6ab28a54766950aa1e16e9521ae5a405@bob.xmpp.org</uri></media><required /><value>145957</value></field>"`

Server response:
`<query xmlns="jabber:iq:register"><data xmlns="urn:xmpp:bob" cid="sha1+fc7819bf6ab28a54766950aa1e16e9521ae5a405@bob.xmpp.org" max-age="0" type="image/png">iVBORw0KGgoAAAANSUhEUgAAAIwAAAA8CAAAAACRYQ2XAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QA/4ePzL8AAAAHdElNRQfkCQIRGxPWdBrNAAAMs0lEQVRo3u1ZaVxURxL/v2EOhlNFFOQQUAgiIuCBQhSPzYpmJT8QY7LqgiZq1Bg10ahoVl1jVtxsNmoiMV4YiVlx1WiioEYioigRwx1AETmUe4YZBhjmerUf3gzMIKBmNbsftr+8113V/f6vqrqqq5oh/O803v8QFvB/sy+RUlJWwA6Z0QsL81upSZ6Sll3rO8rH3t7alfmvgmGzTxwKnDjGy0FEOjBm0EDw3wKjrb6RaRXqbScyloiWYeXmYjPWxGjpuTf1lYihB6u6o+gyUt7mKTv7zx9MetiwL3umNkiNwDxvNZV+cn31q2LmyZifLxh5Rop9uKf42fsZlgeAbZPU1sj53r4qM8ve2WuPmQ+yy06dGuX45Ni7SuaeB/MoCqna9orI4U5t5dXsNjOrYM+2dNmMyQ52gb2sq7ZZ2TfnKv+tOUPw68CsGdMc7796hMmulF9jLE875p6eX3pD7CuVqKIjPVQtWqEu7Tg/qCpolcZUBUpxY3/u7W7Yxrg+M61aFf1/5/+rwMw75z3vm+VRxOcBxKBN/IuqKM6snhfeNGHstmTxy9PdLMtOHbcNWRJkx7L84gxp3rG1MfwhHaKsqCo9OUm9oJ8QkCYcHh411ZYpKSiT28z0eXowBctWZcdLHVYEQG7vUXZ34L3DoVcbrKcMVjZ7KbeFzZvOB3QwU/9yKddx1jgAUFVoj+yM8XOabkU8oPGkPFf0u4uig/+cqa0+e4GNG24OAPVZhU3OkQ5PCYbGnHYBO8+uPN9xmOwHr+BjM0Il+fdWz2Kqki4NnOfX32DqrDzn7CXPdQEiAFAKdmYMuRjyphuVXYHty4PbrLKOn5jclBrCj4o2LCy5ViQdG/V0YBQjygEsCnpTU1OhHCFvGalpPhSfGMrKziR5JErNjCfpKpLyZ4cbHHm69PZJoZ9COOwFD+vW8ryCHOWGuXYvpLh38lddKZdGhTxJZDe05I1ERG/uJyIiloh023yriC6GhKSSa0MXx9maONrvckevsXG1bfA770z16cd3X3jwp6lxxDKsCX/uPz649nhn3Qkm8oERGCKixOAzlBU67hxL5FpBREQao4ltRxedazFEn7hlRJX5xdUtOiKitMHqVgsiIjo0L83Af2VyUVr1Y8B0OL2SWidTkWV9si5w15Wo2f07dovmWkOws6EjjrSMWbSdez9f/Tng4mIgTWRLrfoBAG4zHyhiOXMJXX3Vokw4+REX2G7+qJp0S+rJRDISh4O3N79zXkZEBslUCde/v/uWruNH5Kt4yUREF6dVExGVn3s7hSNEJNwI4l5SSaElvcaalMSW5NQb60+XfTJX/Yhkfnjpn/ampvR61MMPX1npYTxWMeT1gqpvvx421KW/NV+raKwauj1JHGRe82kKABRu0rmvq40GgNCrjCcA4DV/nRXAVNj0BVpyx4Dx0vI1AijNBAyp2lTiPv7+OuoSm+Qp+c3WptJ7Pyd1/nfDgRojud5x8/N7WFAieajW6AAzgdD8wMxJ6z/cvBYA1qZ8OVrSnhQNACH7+o4CALyqLSn28kXFB+N34HhcmgWgqpHYuokVWgvGXKjmsTwqNvM2AdN+JmuBERa2vb7w6A+LlznwAc3xVZ2EPB/AyWna/Qf1MqWWL+4zwHnADXatY9AEAN9b5QMOiyMBAD53f+K8DBVXqxNcZ09Mi2fi7ze1A7C0dKm6SXylUmzXl0T2YNasNAGjjXTfOMhIKPnZWc0Z22f1B4ANQiPCjXUAAHd3Yz+15tqgjHGChzPrAcBOBACwCIvhIhzj69syrLi4r/nSpQnF4SXcxE5L7+YIUUafA0Clq34ofMiYmvAlAFC7oTbAKGgWBnWzwOUIj5kRsUfS7QGgWB9lE+w66FYjR5KG5SEmRpvWYP/ofIWbSRJ34QUA2Le0QzKXptz/FADwxZGRRtNaNYMe8ZgW+GDh7EbP5Ue4WJj4d33M/rOJl5cmygDwp/YhVdcVZHJ3EzBqPpASKSs3DNlINpznA8Cu5Nu2RvMauI7xASh3XJGjPfjLF7G7HgK4wNP/ZuzPBrQyAHBw2QZ1KwtBQ9bdLmB2JolMd5M2/4B4/sCvOiJP7OsOALD3X7P9U4x3NrexjpyYHOg5QKSqv/vzj7k7Po8BYOvNqxs5P6Ys8Rs9q1sM5/PirEd7jhZWldlL/BYx92zGBQQXftoQMYoBQGAA4KMuNtPnC9XYwJG/dAxV3owDgJ+bA6TvGac65S9xQp9vlbpCra4b4BW4fAb2lALA0JrYxacOeH5uSM0OAafS5M43J9rfPD24UuKXGGmzz8u9bXWlctmcgMwt8PJWtgZbAwAxpmDCzAf72RgNpQfYAcBw+/oH91vVAIAXLAG8wQIAojWCP3zYwfxABADiKXsDwgMEQI2tgDFjkOGvGCOSpDoJEltGfGu/1XqfVBu1X9u2QlB0aqbr2DdGWrKbzKcBSIk/3QWMU5TIRI2tnM8RubiMopIC7kBq21mxUJlw6y3tIkjHaGt/zJg0zrX2zj7e8EyJR5rD+CvrHGyOJpatw0CsXnmUATlO2pJ76VhpVNbhGgD4Uyav2yNEoY8hNu1d2m1I1c3ngvTpm/n3e4y7Ol3tiaUrRnlYugR6hy28Q2oiah1bTkQUWqkP8VUJgf2tkomIPlrfwxGiVzB7LhE1WhjOJjlFVy9kEGm7AVNIRDqJu2uLRFmbGZTFDWbOJiIqWdV5GooO3FymozrH1h6OEJ3NuqRSpyPGTCS2MGik741zr9r01Xf8AG8A2fJ+mpEm02XHUqy/BnjCBxaWljAfuHUXt0NHpQCA59c7DMulX7r0j+mrl3yxzOKxSVxg+ppqmdbcKTLU8HnMzUs9P7afKVsAjmV9tSZdscSQptxOc3eZAwAnFxxQWAOYtpCzLzO+lg8wf8icyHFWb9vis//WjrMPLvd07OxUE+XfqFaRjogo50SGgZ4yNPARpRRMibntvV9KRERp37ydqHBVEhGNyl65hoiIdkS1EBGxzjVERJcXc7PY2N8TEVs1/cVK9jE2c8DEHlds6HifsPj1Is5Gi+sMYyrn5L+5bz2RVZ/41saFBZQzl4gof4IqZwBHn//H68RSjQU3YSA3mONxi4hI5vln3uYebMaciy7WdiblR0cFl6wKAcvp2jeHvTPizG7z8X1eHsSpX/hK0meieJvBeW4vjZ6I1lmpALD+XeHwSYv2A0DC8R3Wc53zYwZwMVFnBoA2ho8GgC2vbn333ehNnt2pqfVyd1v1I04yF+uIwmILqr4KnTbj47NfbXJxTeMknGGnVdQlxyKqkogOxhMR3XyxjUhitlUvW7WWtPqDfIKKiCjTrZyISOtQQ1SxZl5td2rS1fUCxnXVnfrXohecKaxKOUcsEWUwuRyDsJXyZ0wpCNzVUBw1p5mIqE8REVG9d1LHIqyxaajW7iYior/GEBHRX7qtXLEPqSNjehTMZ15/86H0OYtPKfSE7725p+2t2b7fEe3hLwz5noiocfHXeklXtmu65FqbdERE2W1ERORewo3K2nsuo2llJt0zCwzZwTahlujK8gj9XA2f83mWE5KIiBo/3l+vJiLavtPwN+q8w+kma5311BGRjEue2s/1lsTVJBBRRdJEUzCNkxLvENGsRiLOW142VAoH1nAbYLoxu+K9F6WdnX+9PGpPWScxfBURVVgqniCjLBpBZUe3v1/UhZ634ZMzdXS9U+KGtGlILRFRo900Y+7P9pqoRnVtZ+yR23olxQ+9TkTxIdwqYe29ZZRs26G6Jp/oLmklRjjJ7Gw1AzV8aOecBIBvX+FqAKUAgNSI8528Bd/5v2Ti0YXBThn5RYfDgxt4rofi5voDmo83AAAOWoh6S/xrvWO/7CEXVlxf2UxEW3YTEe2JbCEiVl8JOFi69kcDV1ZOdxp4kHw4cmJEVJ+IvdVEVGrL8Yy/0N2HOkoi2galR08pxH3rfjygbXjmAAAx9WGjB5Uuvu4IAGpBs9xJXy7Rsvxu72ia1XlN1QFmvtYADh+4DgDqvjU2vZZEHt+OvUVEROfXRroNK+V8XjGpCoulGpa0bQ0tvUzVHzfYaX8nIqJrntSrZJ6gqQPXRgNAu0Kf/zQ5VdijKll2t91h6iC/J1ihzaZ6AAC85fE+/kPJkOyNPJP+nO+JiHTFxfcUT3iN0I97+v70mGLRk7TMECPDa969/qkvEqbHFbFEZNX0H6sJQPGO37+mt9L6U7e2Oj9t/b7lY4GluzMvVM48i7uDgriiqPHu1laC+jdaD7k9/W1CVdrP5uYlXpufzUWG+vZPUmFD5bXmhFmCX3e78UupYBrvWd2q1JQUi/sFODF45o35/732/8E8Zfs3cOuGdYZQNSkAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjAtMDktMDJUMTU6Mjc6MTkrMDI6MDCc1KNXAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIwLTA5LTAyVDE1OjI3OjE5KzAyOjAw7Ykb6wAAAABJRU5ErkJggolQTkcNChoKAAAADUlIRFIAAAAoAAAAPAEAAAAAPMLFTQAAAARnQU1BAACxjwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAAOpgAABdwnLpRPAAAAAJiS0dEAAHdihOkAAAAB3RJTUUH5AkCERsT1nQazQAAABBJREFUGNNj+A8CDKMkjUkAKsYq5D2hXoMAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjAtMDktMDJUMTU6Mjc6MTkrMDI6MDCc1KNXAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIwLTA5LTAyVDE1OjI3OjE5KzAyOjAw7Ykb6wAAAABJRU5ErkJggg==</data><username>victorsps</username><password>a25160920</password><instructions>You need a client that supports x:data and CAPTCHA to register</instructions><x xmlns="jabber:x:data" type="form"><instructions>Choose a username and password to register with this server</instructions><field type="hidden" var="FORM_TYPE"><value>urn:xmpp:captcha</value></field><field label="User" var="username" type="text-single"><required /><value>victorsps</value></field><field label="Password" var="password" type="text-private"><required /><value>a25160920</value></field><field type="fixed" var="captcha-fallback-text"><value>If you don't see the CAPTCHA image here, visit the web page.</value></field><field type="hidden" var="captchahidden"><value>workaround-for-psi</value></field><field label="CAPTCHA web page" var="captcha-fallback-url" type="text-single"><value>http://jabber.freenet.de/captcha/13382908590620806174/image</value></field><field type="hidden" var="from"><value>jabber.freenet.de</value></field><field type="hidden" var="challenge"><value>13382908590620806174</value></field><field type="hidden" var="sid"><value>agsXMPP_1</value></field><field label="Enter the text you see" var="ocr" type="text-single"><media xmlns="urn:xmpp:media-element"><uri type="image/png">cid:sha1+fc7819bf6ab28a54766950aa1e16e9521ae5a405@bob.xmpp.org</uri></media><required /><value>145957</value></field></x></query><error xmlns="jabber:client" code="405" type="cancel"><not-allowed xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" /></error>
`
Will be happy for any help!

**Comment by nathan130200** [comment]
After some search on internet, i've found how XEP-0158 (Captcha Forms) works. You sent an wrong request to the server, when server reply with instructions how to fill the form, you need just respond with required fields.

See in this example https://xmpp.org/extensions/xep-0158.html#register after server send instructions to register, you need to fill required fields with correct values (also include all hidden fields). Also this feature (Captcha forms) isn't implemented in this library, and you need acess captcha image.

Correct way to respond this query:

<b>Example 11.</b> Host Returns Registration and Challenge Fields to Entity
```xml
<iq type='result' xml:lang='en' id='reg1'>
  <query xmlns='jabber:iq:register'>
    <x xmlns='jabber:x:data' type='form'>
      <field type='hidden' var='FORM_TYPE'>
        <value>jabber:iq:register</value>
      </field>
      <field type='hidden' var='challenge'><value>F3A6292C</value></field>
      <field type='hidden' var='sid'><value>reg1</value></field>
      <field type='hidden' var='answers'><value>3</value></field>
      <field var='ocr' label='Enter the text you see'>
        <media xmlns='urn:xmpp:media-element'
               height='80'
               width='290'>
          <uri type='image/jpeg'>
            http://www.victim.com/challenges/ocr.jpeg?F3A6292C
          </uri>
        </media>
      </field>
      <field label='93C7A' type='text-single' var='SHA-256'/>
      <field type='text-single' var='username'>
        <required/>
      </field>
      <field type='text-private' var='password'>
        <required/>
      </field>
    </x>
    <instructions>
      To register, visit http://www.victim.com/register.html
    </instructions>
    <x xmlns='jabber:x:oob'>
      <url>http://www.victim.com/register.html</url>
    </x>
  </query>
</iq>
```

<b>Example 12.</b> Entity Provides Required Information In-Band
```xml
<iq type='set' xml:lang='en' id='RANDOM UNIQUE ID OR SEQUENTIAL ID FOR PACKET IDENTIFICATION'>
  <query xmlns='jabber:iq:register'>
    <x xmlns='jabber:x:data' type='submit'>
      <field var='FORM_TYPE'>
        <value>jabber:iq:register</value>
      </field>
      <field var='challenge'><value>CHALLENGE SENT BY SERVER</value></field>
      <field var='sid'><value>SID SENT BY SERVER</value></field>
      <field var='answers'><value>HOW MANY ANSWERS HAVE</value></field>
      <field var='ocr'><value>OCR CODE TAKEN FROM IMAGE</value></field>
      <field var='username'><value>USERNAME TO REGISTER</value></field>
      <field var='password'><value>PASSWORD TO REGISTER</value></field>
    </x>
  </query>
</iq>
```

Note that these fields that should be filled, is determined by server.
